### ISSUE TITLE
[Suggestions Included] Paths seems to prevent sheep from being able to eat in pens.

### ISSUE THREAD

**Issue by tacusin** [Corosauce/DesirePaths#6]
Sheep kept in pens seem to be prevented from eating once they trample all of their grass. 3 Suggestions: '1'sheep can eat the "reduced" grass from the paths the mod adds to the game, and when they do it becomes vanilla dirt. '2'If a block gets worn down to level 6 (basically a dirt block) and a sheep steps on the block, it becomes a vanilla dirt block. '3'pathway blocks with some grass left on them (worn path 1-5), can still spread grass to adjacent vanilla dirt blocks nearby.

**Comment by Corosauce** [comment]
Yeah I think I'm going to inject AI into the sheep so I can add custom eatable blocks, as for the rules around that you are on the right track, I'm not fond of the idea of using vanilla dirt given how grass can insta restore it to full grass, but it might be required to solve this issue when they've trampled so much, I'll at least add it as a config option.

**Comment by tacusin** [comment]
yea i'm with you, I like the idea of unused paths slowing reverting back to grass, which is why I suggested that only if a sheep walks over a worn path does it get turned to dirt. any grass that comes back would probably either quickly get trampled up or eaten anyways... maybe instead... it'd be more work... but have a special "sheep worn" block that grass can spread to and it becomes worn 4 instead of a full grass block (provided sheep can eat worn blocks).. this way it's never fully grass suddenly, but sheep can still eat from it turning it back into a "sheep worn" block.

Or... an idea that'd (maybe) be a bit less work, sheep don't trample grass, instead when they eat grass blocks, they get worn down. could kinda simulate grazing...

**Comment by Corosauce** [comment]
Good ideas there too!

Decided to keep it simple to start, but more revisions might be needed.

- Sheep grazing wears grass down 1 stage instead of fully to dirt
- Sheep can graze worn grass of any stage as long as its not the full dirt version
- Sheep wear grass down at 10% of the rate of other entities

Works well enough for pens with only sheep of good enough size, but might be an issue if you mix animals together, in the picture below only the big sheep only pen has plenty of grass.

[http://share.coros.us/files/2018-11-30_22.10.14.png](http://share.coros.us/files/2018-11-30_22.10.14.png)

https://github.com/Corosauce/DesirePaths/commit/974e76bd1bedb18b7f09ad42e6c781002718f196

Testing then pushing this with other changes as version 1.2.

**Comment by tacusin** [comment]
sound cool, I'll most likely let you know my personal observations after a couple of days, maybe as long as a week..
